export const TMDB = {
  apiBaseUrl: 'https://api.themoviedb.org/3',
  imageBaseUrl: 'https://image.tmdb.org/t/p',
  language: 'pt-BR',
  region: 'BR',
  posterSize: 'w342',
  backdropSize: 'w1280',
  profileSize: 'w185',
  providerLogoSize: 'w92',
  searchDebounceMs: 500,
  requestTimeoutMs: 15_000,
  catalogRequestTimeoutMs: 15_000,
  catalogRequestRetryCount: 1,
  catalogRequestRetryDelayMs: 800,
  detailsRequestTimeoutMs: 20_000,
  detailsRequestRetryCount: 1,
  detailsRequestRetryDelayMs: 800,
  catalogCacheTtlMs: 10 * 60 * 1000,
  searchCacheTtlMs: 5 * 60 * 1000,
  personCreditsLimit: 20,
  detailsCacheTtlMs: 30 * 60 * 1000,
} as const;
